name: Telegram message
on:
  pull_request:
    branches: [ "main" ]
jobs:

  build:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: View github environment
        run: |
          echo github.event.number = ${{ github.event.number  }}
          echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
          echo github.event.issue.number = ${{ github.event.issue.number }}
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            👨‍💻 *New PR Updates from ${{ github.actor }}*
            
            ⭐️ *Latest commit*: ${{ github.event.commits[0].message }}     ${{github.event.issue.number}}
            ${{github.event.number}}
            
            🚀 *PR*: https://github.com/${{ github.repository }}
            
            🛠️ *Changes*: https://github.com/${{ github.repository }}/commit/${{github.sha}}
