name: Telegram message
on: [push]
jobs:

  build:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TEGRAM_HIEU }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Sent from GitHub
